### ISSUE TITLE
Use Py_INCREF to increment Py_None refcount

### ISSUE THREAD

**Issue by tekknolagi** [eliphatfs/yapyjit#1]
Manually writing to `Py_None->ob_refcnt` may not be necessary with current C++ compilers. They should be able to turn a loop into an add.

https://github.com/eliphatfs/yapyjit/blob/199cbf14d0f4f5dd1148bce9a9c2fb8e32ee0e21/src/binding_jit_entrance.cpp#L141-L144

I have modified the original source into a small repro. Here is a version of the original, with `ob_refcnt += N`:
https://godbolt.org/z/eoYEcsaK8

And here is with a loop `for (...) Py_INCREF(...)`:
https://godbolt.org/z/x9G5Pdodx

And here is a snippet with an inline function, which I think is the case in CPython these days:
https://godbolt.org/z/Mr89reMWe

You can see that the corresponding asm for all snippets just contains `sub`+`add`+`mov`. This means you can use a nice macro and not worry about performance here.

**Comment by juncheng1226** [comment]
亲爱的大人，您的信息我已收到，祝您平安富贵吉祥...and so on~~~

**Comment by eliphatfs** [comment]
Thank you for your insights and suggestions! I will change that soon when I have time on this project.

**Comment by eliphatfs** [comment]
> 亲爱的大人，您的信息我已收到，祝您平安富贵吉祥...and so on~~~

Hi there, it seems that you watched my repository and your email has auto-reply on. Could you please turn off that so my issues won't be spammed?

您好，似乎您关注了这个仓库，但您的电子邮件有自动回复功能，在issue下面会添加无关的信息。能否请您修改一下相关的配置？
